import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import 'boxicons/css/boxicons.min.css';
import Header from "../components/General/Header";
import { Providers } from "./providers";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andin | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href='https://cdn.boxicons.com/3.0.3/fonts/basic/boxicons.min.css' rel='stylesheet'></link>
      </head>
      <body
        className={`${outfit.className} bg-linear-to-r from-purple-950 to-blue-950 min-h-screen`}
      >
        <div className="max-w-5xl mx-auto flex flex-col my-0 min-h-screen p-2">
          <Header />
          <main className="bg-gray-900 flex-1 relative grid place-items-center">
            <Providers>
              {children}
            </Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
